#!/bin/bash

# needs sublime installed
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime

# Homebrew
if which brew >/dev/null; then
	echo "homebrew already installed"
else
	echo "homebrew not installed, installing now.."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

# Brew Cask
brew tap caskroom/cask
brew tap buo/cask-upgrade
echo 'tools installed with brew cask can be updated via `brew cu`'

# QuickLook plugins for Finder
brew cask install qlcolorcode
brew cask install qlimagesize
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install quicklook-json


# install / update bundler which is needed for installing Gemfile bundles
# not using sudo, since it expects the GEM_HOME to be set to a path inside $HOME
gem install bundler -V --no-ri --no-rdoc
