#!/bin/bash

# needs sublime installed
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime

# Homebrew
if which brew >/dev/null; then
	echo "homebrew already installed"
else
	echo "homebrew not installed, installing now.."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/ehrentfa/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew update

# Brew Cask
brew tap homebrew/cask
brew tap buo/cask-upgrade
brew tap homebrew/cask-fonts
echo 'tools installed with brew cask can be updated via `brew cu`'

# QuickLook plugins for Finder
#brew install --cask qlcolorcode
#brew install --cask qlimagesize
#brew install --cask qlmarkdown
#brew install --cask qlstephen
#brew install --cask quicklook-json

brew install --cask font-fira-code
brew install --cask font-inconsolata-for-powerline

# install / update bundler which is needed for installing Gemfile bundles
# not using sudo, since it expects the GEM_HOME to be set to a path inside $HOME
gem install bundler -V
